const directions=[
['TRUSTED EVIDENCE','Forensic audit / facts before interpretation','Facts → decisions → executions → evidence → limits','document'],['CASE FILE','An investigation dossier built for review','Mission → context → signals → proof → report','case'],['INVESTIGATION WORKBENCH','An IDE for navigating security evidence','Objects + canvas + inspector','workbench'],['SCIENTIFIC LAB','A reproducible experiment notebook','Hypothesis → configuration → observations → conclusion','lab'],['TRACE EXPLORER','A mission rendered as an execution trace','Intent → plan → policy → tools → report','trace'],['KNOWLEDGE MAP','A controlled map of related objects','Mission ↔ target ↔ provider ↔ finding','map'],['ARCHIVE ROOM','Professional records, indexed and versioned','Index → dossier → exhibits → metadata','archive'],['CONSOLE MINIMALE','One intention, then progressive complexity','Ask → run → inspect','minimal'],['OPERATIONS LEDGER','Every decision as an auditable entry','Time | actor | object | action | status','ledger'],['MISSION TIMELINE','Understand the run through its chronology','Launch → scan → extract → correlate → report','timeline'],['DATA TABLE FIRST','Findings are the primary working surface','Filter → compare → select → inspect','table'],['OBSERVATORY','Explore signals and distributions','Query → filters → results → correlation','observatory'],['CODE REVIEW SECURITY','Findings attached to source lines','Files → code → annotations → evidence','code'],['CONTROL DESK','Policy and execution control, made explicit','Policy → capability → decision → execution','control'],['FIELD NOTEBOOK','A rigorous investigator notebook','Observe → annotate → cross-reference','notebook'],['GRAPH PAPER','Technical cartography with real relationships','Mission ↓ providers ↓ executions ↓ findings','graph'],['QUIET PROFESSIONAL','Calm, premium, almost invisible UI','Context → priority → detail','quiet'],['SPLIT INVESTIGATION','Three persistent views, one selection','Signals | investigation | inspector','split'],['EDITORIAL REPORT','Analysis designed to be read and shared','Summary → findings → proof → limits','editorial'],['UNEXPECTED / CONTROLLED EXPERIMENT','A mission as a chain of custody','Request → custody seal → observations → verdict','unexpected']];
const findings=[['CRITICAL','Trivy','Unsafe YAML deserialization','requirements.txt:7','CWE-502'],['HIGH','Gitleaks','Hard-coded API key detected','app.py:12','Secret exposure'],['HIGH','Semgrep','SQL query built by concatenation','app.py:88','CWE-89'],['HIGH','Grype','Vulnerable dependency: requests','requirements.txt:3','CVE-2024-2222'],['ERROR','Bandit','Subprocess uses shell=True','app.py:141','B602'],['ERROR','Semgrep','Path traversal from request input','routes/files.py:44','CWE-22'],['MEDIUM','Checkov','Storage bucket is publicly readable','infra/main.tf:31','CKV_AWS_19'],['MEDIUM','Trivy','Container runs as root','Dockerfile:18','DS002'],['MEDIUM','Semgrep','Missing CSRF protection','app.py:63','CWE-352'],['LOW','Gitleaks','Private key pattern in test fixture','tests/data.txt:4','Secret exposure'],['LOW','Bandit','Possible weak hash algorithm','utils/hash.py:20','B324'],['UNKNOWN','Checkov','Policy result unavailable','infra/main.tf:1','Unknown']];
const providers=[['Semgrep','completed','4 findings'],['Gitleaks','completed','2 findings'],['Trivy','completed','2 findings'],['Bandit','completed','2 findings'],['Checkov','completed','1 finding'],['Grype','not executed','dependency source unavailable']];
let current=0;const fav=JSON.parse(localStorage.getItem('agnt-favorites')||'[]');
const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function findingRows(){return findings.map((f,i)=>`<div class="finding sev-${f[0].toLowerCase()}" tabindex="0"><span class="sev">${f[0]}</span><strong>${f[2]}</strong><span class="muted">${f[1]}</span><code>${f[3]}</code><span class="tag">${f[4]}</span><button class="inspect" data-id="${i}">Inspect</button></div>`).join('')}
function evidence(){return `<div class="evidence"><div class="eyebrow">EVIDENCE / SELECTED FINDING</div><h3>Unsafe YAML deserialization</h3><p class="muted">The scanner reports a dangerous loader on an untrusted input path.</p><pre>yaml.load(payload, Loader=UnsafeLoader)</pre><dl><dt>Source</dt><dd>Trivy · CVE-2024-11111</dd><dt>Location</dt><dd>requirements.txt, line 7</dd><dt>Confidence</dt><dd><span class="state high">HIGH</span> declared by provider</dd></dl></div>`}
function standard(kind){let main=`<div class="summary"><div><div class="eyebrow">MISSION / COMPLETED / HIGH CONFIDENCE</div><h1>Repository security assessment</h1><p>Identify exploitable security issues and exposed secrets.</p></div><div class="stats"><b>12</b><span>findings</span><b>6</b><span>providers</span><b>1</b><span>correlation</span></div></div>`;if(kind==='table'||kind==='observatory')main+=`<div class="query"><input placeholder="Filter findings, providers, files…"><span>12 results</span><button>Save view</button></div><div class="data-table">${findingRows()}</div>`;else if(kind==='trace'||kind==='timeline')main+=`<div class="trace">${['Intent received','Plan validated','Policy authorized','Semgrep / Gitleaks / Trivy executed','Findings normalized','Correlation completed','Report archived'].map((x,i)=>`<div class="trace-row"><i>${String(i+1).padStart(2,'0')}</i><strong>${x}</strong><span class="muted">${i===3?'3 providers · 2.8s':'completed'}</span></div>`).join('')}</div><div class="panel"><h2>Findings from execution</h2>${findingRows().slice(0,5)}</div>`;else if(kind==='code')main+=`<div class="code-layout"><aside><b>FILES</b><p>app.py</p><p>routes/files.py</p><p>requirements.txt</p><p>infra/main.tf</p></aside><pre class="source">  84  user = request.args.get("name")
  85  query = "SELECT * FROM users WHERE name = '" + user
  86  return db.execute(query)

<span class="line-error">  88  ← SQL query built by concatenation</span>

  89  audit.log("lookup", user)</pre>${evidence()}</div>`;else if(kind==='map'||kind==='graph')main+=`<div class="relationship"><div class="node root">MISSION<br><small>assessment</small></div><div class="edge e1"></div><div class="node target">TARGET<br><small>example-project</small></div><div class="node provider p1">Semgrep</div><div class="node provider p2">Gitleaks</div><div class="node provider p3">Trivy</div><div class="node finding-node">12 FINDINGS</div></div>${evidence()}`;else main+=`<div class="panel"><h2>What happened</h2><p class="lead">Six providers were selected from the published capability registry. Five produced results. One was not executed because its dependency source was unavailable.</p><div class="provider-list">${providers.map(p=>`<div><strong>${p[0]}</strong><span class="state ${p[1]==='completed'?'done':'unknown'}">${p[1]}</span><span class="muted">${p[2]}</span></div>`).join('')}</div></div><div class="panel"><h2>Priority findings</h2>${findingRows().slice(0,4)}</div>`;return main}
function render(){const d=directions[current];document.body.dataset.theme=d[3];$('#app').innerHTML=`<header class="top"><a class="brand" href="#">AGNT <span>DESIGN LAB</span></a><div class="top-title">20 INTERACTIVE DIRECTIONS <span>· SAME DATASET</span></div><button id="grid">Hide gallery</button><button id="favorite">${fav.includes(current)?'♥':'♡'} Favorite</button></header><main><div class="hero"><div><div class="eyebrow">DIRECTION ${String(current+1).padStart(2,'0')} / 20</div><h2>${d[0]}</h2><p>${d[1]}</p></div><div class="mental"><span>MENTAL MODEL</span><b>${d[2]}</b></div></div><div class="nav"><button id="prev">← Previous</button><div class="dots">${directions.map((_,i)=>`<button class="dot ${i===current?'selected':''}" data-go="${i}" aria-label="Direction ${i+1}">${String(i+1).padStart(2,'0')}</button>`).join('')}</div><button id="next">Next →</button></div><div id="gallery" class="gallery">${directions.map((x,i)=>`<button class="gallery-card ${i===current?'chosen':''}" data-go="${i}"><span>${String(i+1).padStart(2,'0')}</span><strong>${x[0]}</strong><small>${x[1]}</small></button>`).join('')}</div><section class="product">${standard(d[3])}</section></main><div id="drawer" class="drawer hidden">${evidence()}<button id="close">Close</button></div>`;bind()}
function bind(){$('#prev').onclick=()=>{current=(current+19)%20;render()};$('#next').onclick=()=>{current=(current+1)%20;render()};document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{current=+b.dataset.go;render()});$('#favorite').onclick=()=>{fav.includes(current)?fav.splice(fav.indexOf(current),1):fav.push(current);localStorage.setItem('agnt-favorites',JSON.stringify(fav));render()};$('#grid').onclick=()=>{const gallery=$('#gallery');gallery.classList.toggle('hidden');$('#grid').textContent=gallery.classList.contains('hidden')?'Browse all 20':'Close gallery';if(!gallery.classList.contains('hidden'))gallery.scrollIntoView({behavior:'smooth',block:'start'})};document.querySelectorAll('.inspect').forEach(b=>b.onclick=()=>$('#drawer').classList.remove('hidden'));$('#close').onclick=()=>$('#drawer').classList.add('hidden');document.onkeydown=keys}
function keys(e){if(e.key==='ArrowRight'){current=(current+1)%20;render()}if(e.key==='ArrowLeft'){current=(current+19)%20;render()}if(e.key==='f'||e.key==='F'){$('#favorite').click()}if(e.key==='Escape'&&!$('#drawer').classList.contains('hidden'))$('#close').click()}
render();